### ISSUE TITLE
Criação do Backup

### ISSUE THREAD

**Issue by werdelesmarcio** [werdelesmarcio/PyTCPScan#1]
Criar uma pasta para guardar os backups e alterações relevantes na aplicação.
![CartãoVisitasMarcio](https://user-images.githubusercontent.com/36682515/63938276-ce537280-ca3a-11e9-8f4d-004dffaa3bec.jpg)

**Comment by matholiveira91** [comment]
não seria melhor criar uma branch ???

**Comment by werdelesmarcio** [comment]
pode ser tb

**Comment by werdelesmarcio** [comment]
Concluido
